Repository JNKRO/code_qualify_backend, pull requests merged in 2023-11, with the labels that each got.

#9 `README.md` を追加する
  README.md
Labels: documentation

#10 `Dockerfile` を検証する
  .github/workfows/docker-lint.yml
Labels: enhancement

#11 `docker-compose.yml` を検証する
  .github/workflows/docker-compose-validate.yml
Labels: enhancement

#20 Dependabot を追加する
  .github/dependabot.yml
Labels: enhancement

#19 `docker-lint.yml` のパス修正
  .github/workflows/docker-lint.yml
Labels: bug

#22 `requirements.txt` を追加する
  requirements.txt
Labels: enhancement

#24 `docker-compose.yml` を追加する
  docker-compose.yml
Labels: enhancement

#23 `Dockerfile` を追加する
  Dockerfile
Labels: enhancement

#25 プロジェクトの初期設定をする
  codequalify/__init__.py
  codequalify/asgi.py
  codequalify/settings.py
  codequalify/urls.py
  codequalify/wsgi.py
  manage.py
Labels: enhancement

#33 Dependabot で Python の依存関係も更新できるように
  .github/dependabot.yml
Labels: enhancement

#35 [CI] Python を静的解析する
  .github/workflows/lint.yml
Labels: enhancement

#38 django rest frameworkの設定完了
  codequalify/settings.py
  codequalify/urls.py
  requirements.txt
Labels: enhancement, dependencies

#41 GitHub OAuth 認証を実装する
  codequalify/settings.py
  codequalify/urls.py
  codequalify/views.py
  requirements.txt
  templates/templates/login.html
Labels: enhancement

#43 SOCIAL_AUTH_GITHUB_KEYを公開しないようにする
  codequalify/settings.py
Labels: enhancement

#45 Add status badge: Lint
  README.md
Labels: documentation, enhancement
